# Generated by Django 4.0.10 on 2023-03-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
                ('coupon_rate', models.DecimalField(decimal_places=3, default=0.0, max_digits=15, null=True)),
                ('maturity', models.DateField(null=True)),
                ('symbol', models.CharField(max_length=250, null=True)),
                ('cusip', models.CharField(max_length=250, null=True)),
                ('next_call_date', models.DateField(null=True)),
                ('callable', models.BooleanField(default=False, null=True)),
                ('last_price', models.DecimalField(decimal_places=3, default=0.0, max_digits=15, null=True)),
                ('last_yield', models.DecimalField(decimal_places=3, default=0.0, max_digits=15, null=True)),
                ('last_trade_date', models.DateField(null=True)),
                ('us_treasury_yield', models.DateField(null=True)),
                ('bond_type', models.CharField(max_length=250, null=True)),
                ('debt_type', models.CharField(max_length=250, null=True)),
                ('offering_date', models.DateField(null=True)),
                ('first_coupon_date', models.DateField(null=True)),
                ('payment_frequence', models.CharField(max_length=250, null=True)),
                ('security_level', models.CharField(max_length=250, null=True)),
                ('price_at_offering', models.DecimalField(decimal_places=3, default=0.0, max_digits=15, null=True)),
                ('moody_rating', models.CharField(max_length=250, null=True)),
                ('sp_rating', models.CharField(max_length=250, null=True)),
                ('default', models.CharField(max_length=250, null=True)),
                ('bankruptcy', models.BooleanField(default=False, null=True)),
                ('call_date', models.DateField(null=True)),
                ('call_price', models.DecimalField(decimal_places=3, default=0.0, max_digits=15, null=True)),
                ('call_frequency', models.CharField(max_length=250, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
